# Generated by Django 4.1.2 on 2022-10-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuarcion',
            new_name='Configuracion',
        ),
    ]
