# Generated by Django 4.1.2 on 2022-10-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
